name: Environments brownbag

on:
  push:
  pull_request: 
  workflow_dispatch:

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  context:
    runs-on: self-hosted
    steps:
      - name: Print github context
        run: echo "${{ toJSON(github) }}" 1>/dev/null
  feature:
    environment: development
    runs-on: self-hosted
    steps:
      - name: First task
        run: echo first task executed
      - name: Second task
        run: echo second task executed
  launching:
    environment: production
    needs: feature
    runs-on: self-hosted
    steps:
      - name: Preparing for launch on prod
        run: echo launch starting...
      - name: Launching
        run: echo launch completed
  publishing:
    environment: public
    runs-on: self-hosted
    steps:
      - name: Preparing step for publishing
        run: echo preparing materials
      - name: Publishing
        run: echo new materials published
  secrets:
    runs-on: self-hosted
    steps:
      - name: Accessing repository variables
        run: echo ${{ vars.USERNAME }}
      - name: Accessing repository secrets
        run: |
          CHECKSUM=`printf ${{ secrets.PASSWORD }} | shasum | awk '{print $1}'`
          [[ $CHECKSUM == 8cb2237d0679ca88db6464eac60da96345513964 ]] && exit 0 || exit 1
  envd_secrets:
    environment: secretly 
    runs-on: self-hosted
    steps:
      - name: Accessing repository variables
        run: echo ${{ vars.USERNAME }}
      - name: Accessing repository secrets
        run: |
          CHECKSUM=`printf ${{ secrets.PASSWORD }} | shasum | awk '{print $1}'`
          [[ $CHECKSUM == 348162101fc6f7e624681b7400b085eeac6df7bd ]] && exit 0 || exit 1
    
      
