name: Print Contexts
on: 
  push: 
    branches: 
      - 'main'
  pull_request:
  release:
    types:
      - published      

permissions:
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: self-hosted 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Cleanup residual files
        run: rm -fr dist/*
      - name: Build wheel
        run: python -m build --wheel --verbose
  publish:
    runs-on: self-hosted
    needs: build
    if: github.event_name == 'release'
    environment:
      name: releasing
      deployment: false
    steps:
      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          packages-dir: dist/*
  print-context:
    runs-on: self-hosted 
    steps:
      - name: Print github context
        run: echo '${{ toJSON(github) }}' 1>/dev/null
