name: CI
on: 
  push: 
    branches: 
      - 'main'
  pull_request:
  release:
    types:
      - published      

permissions:
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: self-hosted 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Cleanup residual files
        run: rm -fr dist/*
      - name: Build wheel
        run: python -m build --wheel --verbose
      - name: Upgrade minor version
        run: sed 's/0.0.5/0.0.6/' pyproject.toml
      - name: Build wheel
        run: python -m build --wheel --verbose
      - name: Upgrade minor version
        run: sed 's/0.0.6/0.0.7/' pyproject.toml
      - name: Build wheel
        run: python -m build --wheel --verbose
  publish:
    runs-on: self-hosted
    needs: build
    if: github.event_name == 'release'
    steps:
      - name: Publish package distributions to TestPyPI
        run: |
          twine upload \
            --repository-url https://test.pypi.org/legacy/ \
            --non-interactive \
            --verbose \
            dist/lreal_pypi_dummy-0.0.5-py3-none-any.whl \
            dist/lreal_pypi_dummy-0.0.6-py3-none-any.whl
