name: Print Contexts
on: 
  pull_request:
  push:
  release:
    types:
      - published      
permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  initial-tasks:
    runs-on: self-hosted 
    steps:
      - name: Run initial tasks
        run: echo 'Execution of initial tasks'
  extra-job:
    runs-on: self-hosted
    needs: initial-tasks
    steps:
      - name: Do some tasks
        run: echo "Tasks executed"
  print-context:
    runs-on: self-hosted 
    steps:
      - name: Print github context
        run: echo '${{ toJSON(github) }}' 1>/dev/null
