name: Print Contexts
on: 
  pull_request:
  push:
  release:
    types:
      - published      
permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  base-context:
    runs-on: self-hosted 
    steps:
      - name: Print github context
        run: echo "${{ toJSON(github) }}" 1>/dev/null
      - name: Print vars context
        run: echo "${{ toJSON(vars) }}" 1>/dev/null
      - name: Print job context
        run: echo "${{ toJSON(job) }}" 1>/dev/null
      - name: Print runner context
        run: echo "${{ toJSON(runner) }}" 1>/dev/null
      - name: Print secrets context
        run: echo "${{ toJSON(secrets) }}" 1>/dev/null
      - name: Print strategy context
        run: echo "${{ toJSON(strategy) }}" 1>/dev/null
      - name: Print env context
        run: echo "${{ toJSON(env) }}" 1>/dev/null
      - name: Print steps context
        run: echo "${{ toJSON(steps) }}" 1>/dev/null
      - name: Print matrix context
        run: echo "${{ toJSON(matrix) }}" 1>/dev/null
      - name: Print needs context
        run: echo "${{ toJSON(needs) }}" 1>/dev/null
      - name: Print inputs context
        run: echo "${{ toJSON(inputs) }}" 1>/dev/null
  extra-job:
    runs-on: self-hosted
    if: github.event_name == 'release'
    steps:
      - name: Do some tasks
        run: echo "Tasks executed"
